### ISSUE TITLE
Error while using custom data

### ISSUE THREAD

**Issue by The-One-Who-Speaks-and-Depicts** [thunlp/VERNet#3]
I am terribly sorry for disturbing you again. I have the following error, while training my model on custom data.
```
Traceback (most recent call last):
  File "../VERNet/model/train.py", line 165, in <module>
    train_model(model, ori_model, args, trainset_reader, validset_reader)
  File "../VERNet/model/train.py", line 89, in train_model
    for inp_tensor, msk_tensor, seg_tensor, score_tensor in trainset_reader:
  File "../VERNet/model/data_loader.py", line 162, in __next__
    return self.next()
  File "/../VERNet/model/data_loader.py", line 174, in next
    torch.LongTensor(inp))
ValueError: expected sequence of length A at dim 1 (got B)
```
where A and B are changing numbers.

The samples of data I am using (sorry for overquoting - you may need this much for reproduction; also, I have tried removing [CLS] and [EOS], and/or diacritics, it did not help):

Croatian (Roman script):
```
{"src":"[CLS] Popijač ističe i kako postoji interes investitora pogotovo u energetici i turizmu , da su deseci projekata u tim djelatnostima u odmakloj fazi , a ni jedan nije ispod sto milijuna eura . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Popijač ističe","Popijač ističe i","ističe i kako","i kako postoji","kako postoji interes","postoji interes investitora","interes investitora pogotovo","investitora pogotovo u","pogotovo u energetici","u energetici i","energetici i turizmu","i turizmu ,","turizmu , da",", da su","da su deseci","su deseci projekata","deseci projekata u","projekata u tim","u tim djelatnostima","tim djelatnostima u","djelatnostima u odmakloj","u odmakloj fazi","odmakloj fazi ,","fazi , a",", a ni","a ni jedan","ni jedan nije","jedan nije ispod","nije ispod sto","ispod sto milijuna","sto milijuna eura","milijuna eura .","eura . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Grgur Nazijanski : Bog je uvijek bio , jest i bit će . [EOS]","src_lab":"c c c c c c c c c c c c c c c","hyp":["[CLS] Grgur Nazijanski","Grgur Nazijanski :","Nazijanski : Bog",": Bog je","Bog je uvijek","je uvijek bio","uvijek bio ,","bio , jest",", jest i","jest i bit","i bit će","bit će .","će . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Na koncu je i broj stranih ulagača bio samo simboličan , kao i iznos koji su uložili \" , rekao je Sejdiu za SETimes . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Na koncu","Na koncu je","koncu je i","je i broj","i broj stranih","broj stranih ulagača","stranih ulagača bio","ulagača bio samo","bio samo simboličan","samo simboličan ,","simboličan , kao",", kao i","kao i iznos","i iznos koji","iznos koji su","koji su uložili","su uložili \"","uložili \" ,","\" , rekao",", rekao je","rekao je Sejdiu","je Sejdiu za","Sejdiu za SETimes","za SETimes .","SETimes . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Utjecaj Turske ima snažne implikacije za BiH [EOS]","src_lab":"c c c c c c c c c","hyp":["[CLS] Utjecaj Turske","Utjecaj Turske ima","Turske ima snažne","ima snažne implikacije","snažne implikacije za","implikacije za BiH","za BiH [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Odbitci po prihodima od intelektualnog vlasništva bit će smanjeni s 40% na 20% kako bi se umanjilo izbjegavanje plaćanja poreza . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Odbitci po","Odbitci po prihodima","po prihodima od","prihodima od intelektualnog","od intelektualnog vlasništva","intelektualnog vlasništva bit","vlasništva bit će","bit će smanjeni","će smanjeni s","smanjeni s 40%","s 40% na","40% na 20%","na 20% kako","20% kako bi","kako bi se","bi se umanjilo","se umanjilo izbjegavanje","umanjilo izbjegavanje plaćanja","izbjegavanje plaćanja poreza","plaćanja poreza .","poreza . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Svi ovi podaci ruše tezu da su ljudi nakon školovanja potpuno pripremljeni za savjestan rad na poslovnim izazovima . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Svi ovi","Svi ovi podaci","ovi podaci ruše","podaci ruše tezu","ruše tezu da","tezu da su","da su ljudi","su ljudi nakon","ljudi nakon školovanja","nakon školovanja potpuno","školovanja potpuno pripremljeni","potpuno pripremljeni za","pripremljeni za savjestan","za savjestan rad","savjestan rad na","rad na poslovnim","na poslovnim izazovima","poslovnim izazovima .","izazovima . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Centar za socijalnu skrb priznaje korisniku ovo pravo na temelju prethodno pribavljenog mišljenja pružatelja usluga o vrsti , trajanju i učestalosti pružanja usluge . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Centar za","Centar za socijalnu","za socijalnu skrb","socijalnu skrb priznaje","skrb priznaje korisniku","priznaje korisniku ovo","korisniku ovo pravo","ovo pravo na","pravo na temelju","na temelju prethodno","temelju prethodno pribavljenog","prethodno pribavljenog mišljenja","pribavljenog mišljenja pružatelja","mišljenja pružatelja usluga","pružatelja usluga o","usluga o vrsti","o vrsti ,","vrsti , trajanju",", trajanju i","trajanju i učestalosti","i učestalosti pružanja","učestalosti pružanja usluge","pružanja usluge .","usluge . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Sporazumom su predviđeni međunarodni razgovori o stabilnosti i sigurnosti u Južnoj Osetiji i Abhaziji , drugoj pobunjenoj gruzijskoj regiji . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Sporazumom su","Sporazumom su predviđeni","su predviđeni međunarodni","predviđeni međunarodni razgovori","međunarodni razgovori o","razgovori o stabilnosti","o stabilnosti i","stabilnosti i sigurnosti","i sigurnosti u","sigurnosti u Južnoj","u Južnoj Osetiji","Južnoj Osetiji i","Osetiji i Abhaziji","i Abhaziji ,","Abhaziji , drugoj",", drugoj pobunjenoj","drugoj pobunjenoj gruzijskoj","pobunjenoj gruzijskoj regiji","gruzijskoj regiji .","regiji . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Unatoč širokom političkom konsenzusu oko obrazovnih reformi , koje su usmjerene na unaprjeđenje akademskih standarda i studenata i nastavnog osoblja koji su već dugo u opadanju , prošlog tjedna održana su \" prosvjedna sjedenja \" u školama i jedan veliki ulični prosvjed , što su uglavnom podržale profesorske udruge i studentske skupine povezane s lijevim strankama . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Unatoč širokom","Unatoč širokom političkom","širokom političkom konsenzusu","političkom konsenzusu oko","konsenzusu oko obrazovnih","oko obrazovnih reformi","obrazovnih reformi ,","reformi , koje",", koje su","koje su usmjerene","su usmjerene na","usmjerene na unaprjeđenje","na unaprjeđenje akademskih","unaprjeđenje akademskih standarda","akademskih standarda i","standarda i studenata","i studenata i","studenata i nastavnog","i nastavnog osoblja","nastavnog osoblja koji","osoblja koji su","koji su već","su već dugo","već dugo u","dugo u opadanju","u opadanju ,","opadanju , prošlog",", prošlog tjedna","prošlog tjedna održana","tjedna održana su","održana su \"","su \" prosvjedna","\" prosvjedna sjedenja","prosvjedna sjedenja \"","sjedenja \" u","\" u školama","u školama i","školama i jedan","i jedan veliki","jedan veliki ulični","veliki ulični prosvjed","ulični prosvjed ,","prosvjed , što",", što su","što su uglavnom","su uglavnom podržale","uglavnom podržale profesorske","podržale profesorske udruge","profesorske udruge i","udruge i studentske","i studentske skupine","studentske skupine povezane","skupine povezane s","povezane s lijevim","s lijevim strankama","lijevim strankama .","strankama . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] \" U ovoj su zemlji u tijeku mnoge reforme u području pravosuđa , sloboda i zaštite , ali kako bi došlo do stvarnih promjena , mora se promijeniti svijest u glavama policajaca , administrativnog i zatvorskog osoblja . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] \" U","\" U ovoj","U ovoj su","ovoj su zemlji","su zemlji u","zemlji u tijeku","u tijeku mnoge","tijeku mnoge reforme","mnoge reforme u","reforme u području","u području pravosuđa","području pravosuđa ,","pravosuđa , sloboda",", sloboda i","sloboda i zaštite","i zaštite ,","zaštite , ali",", ali kako","ali kako bi","kako bi došlo","bi došlo do","došlo do stvarnih","do stvarnih promjena","stvarnih promjena ,","promjena , mora",", mora se","mora se promijeniti","se promijeniti svijest","promijeniti svijest u","svijest u glavama","u glavama policajaca","glavama policajaca ,","policajaca , administrativnog",", administrativnog i","administrativnog i zatvorskog","i zatvorskog osoblja","zatvorskog osoblja .","osoblja . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Da bi se kriminalci sankcionirali , moraju se dijeliti i razmjenjivati dokazi diljem regije i moraju se uspostaviti mehanizmi za olakšanje toga , kazao je EULEX . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Da bi","Da bi se","bi se kriminalci","se kriminalci sankcionirali","kriminalci sankcionirali ,","sankcionirali , moraju",", moraju se","moraju se dijeliti","se dijeliti i","dijeliti i razmjenjivati","i razmjenjivati dokazi","razmjenjivati dokazi diljem","dokazi diljem regije","diljem regije i","regije i moraju","i moraju se","moraju se uspostaviti","se uspostaviti mehanizmi","uspostaviti mehanizmi za","mehanizmi za olakšanje","za olakšanje toga","olakšanje toga ,","toga , kazao",", kazao je","kazao je EULEX","je EULEX .","EULEX . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Iako odluka parlamenta predstavlja značajan doprinos napretku kojeg je Turska postigla na putu ka ostvarivanju standarda EU , najmanje još 20 članaka ustava mora biti izmijenjeno kako bi se dokument uskladio s propisima EU . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Iako odluka","Iako odluka parlamenta","odluka parlamenta predstavlja","parlamenta predstavlja značajan","predstavlja značajan doprinos","značajan doprinos napretku","doprinos napretku kojeg","napretku kojeg je","kojeg je Turska","je Turska postigla","Turska postigla na","postigla na putu","na putu ka","putu ka ostvarivanju","ka ostvarivanju standarda","ostvarivanju standarda EU","standarda EU ,","EU , najmanje",", najmanje još","najmanje još 20","još 20 članaka","20 članaka ustava","članaka ustava mora","ustava mora biti","mora biti izmijenjeno","biti izmijenjeno kako","izmijenjeno kako bi","kako bi se","bi se dokument","se dokument uskladio","dokument uskladio s","uskladio s propisima","s propisima EU","propisima EU .","EU . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Godišnja skupština EBRD-a u Beogradu , podrška stranim investicijama u Srbiji i Crnoj Gori [EOS]","src_lab":"c c c c c c c c c c c c c c c c","hyp":["[CLS] Godišnja skupština","Godišnja skupština EBRD-a","skupština EBRD-a u","EBRD-a u Beogradu","u Beogradu ,","Beogradu , podrška",", podrška stranim","podrška stranim investicijama","stranim investicijama u","investicijama u Srbiji","u Srbiji i","Srbiji i Crnoj","i Crnoj Gori","Crnoj Gori [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Druga scena vezana je uz Isusovu zapovijed Šimunu ( i to je riječ Božja ) da izveze na pučinu i baci mreže za lov ( 5,4 ) . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Druga scena","Druga scena vezana","scena vezana je","vezana je uz","je uz Isusovu","uz Isusovu zapovijed","Isusovu zapovijed Šimunu","zapovijed Šimunu (","Šimunu ( i","( i to","i to je","to je riječ","je riječ Božja","riječ Božja )","Božja ) da",") da izveze","da izveze na","izveze na pučinu","na pučinu i","pučinu i baci","i baci mreže","baci mreže za","mreže za lov","za lov (","lov ( 5,4","( 5,4 )","5,4 ) .",") . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Bill Gates boravio je u Ateni kako bi obilježio otvaranje novog \" inovacijskog središta \" tog softverskog diva . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Bill Gates","Bill Gates boravio","Gates boravio je","boravio je u","je u Ateni","u Ateni kako","Ateni kako bi","kako bi obilježio","bi obilježio otvaranje","obilježio otvaranje novog","otvaranje novog \"","novog \" inovacijskog","\" inovacijskog središta","inovacijskog središta \"","središta \" tog","\" tog softverskog","tog softverskog diva","softverskog diva .","diva . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Na većini švicarskih autocesta brzina je ograničena na 120 km h , a kako su im kazne drakonske , velikoj većini tamošnjih vozača ne pada na pamet značajnije prekoračiti brzinu . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Na većini","Na većini švicarskih","većini švicarskih autocesta","švicarskih autocesta brzina","autocesta brzina je","brzina je ograničena","je ograničena na","ograničena na 120","na 120 km","120 km h","km h ,","h , a",", a kako","a kako su","kako su im","su im kazne","im kazne drakonske","kazne drakonske ,","drakonske , velikoj",", velikoj većini","velikoj većini tamošnjih","većini tamošnjih vozača","tamošnjih vozača ne","vozača ne pada","ne pada na","pada na pamet","na pamet značajnije","pamet značajnije prekoračiti","značajnije prekoračiti brzinu","prekoračiti brzinu .","brzinu . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] \" Razlog je što integraciju u EU i NATO , što je regiji politički potrebno , kao i osiguranje energetske sigurnosti , Turska ne može isporučiti \" . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] \" Razlog","\" Razlog je","Razlog je što","je što integraciju","što integraciju u","integraciju u EU","u EU i","EU i NATO","i NATO ,","NATO , što",", što je","što je regiji","je regiji politički","regiji politički potrebno","politički potrebno ,","potrebno , kao",", kao i","kao i osiguranje","i osiguranje energetske","osiguranje energetske sigurnosti","energetske sigurnosti ,","sigurnosti , Turska",", Turska ne","Turska ne može","ne može isporučiti","može isporučiti \"","isporučiti \" .","\" . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Ovi materijali važan su dodatak hrani svagdje u svijetu . [EOS]","src_lab":"c c c c c c c c c c c c","hyp":["[CLS] Ovi materijali","Ovi materijali važan","materijali važan su","važan su dodatak","su dodatak hrani","dodatak hrani svagdje","hrani svagdje u","svagdje u svijetu","u svijetu .","svijetu . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Ovi krediti Svjetske banke bit će odvojeni od strategije banke za pomoć zemlji . [EOS]","src_lab":"c c c c c c c c c c c c c c c c","hyp":["[CLS] Ovi krediti","Ovi krediti Svjetske","krediti Svjetske banke","Svjetske banke bit","banke bit će","bit će odvojeni","će odvojeni od","odvojeni od strategije","od strategije banke","strategije banke za","banke za pomoć","za pomoć zemlji","pomoć zemlji .","zemlji . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Planiran je rast doprinosa za drugi stup mirovinskog osiguranja , što bi značilo pad u prvom stupu , no toga nema u proračunu , a Vlada je već ove godine popustila pod pritiskom i znatno ublažila raniji odlazak u mirovinu . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] Planiran je","Planiran je rast","je rast doprinosa","rast doprinosa za","doprinosa za drugi","za drugi stup","drugi stup mirovinskog","stup mirovinskog osiguranja","mirovinskog osiguranja ,","osiguranja , što",", što bi","što bi značilo","bi značilo pad","značilo pad u","pad u prvom","u prvom stupu","prvom stupu ,","stupu , no",", no toga","no toga nema","toga nema u","nema u proračunu","u proračunu ,","proračunu , a",", a Vlada","a Vlada je","Vlada je već","je već ove","već ove godine","ove godine popustila","godine popustila pod","popustila pod pritiskom","pod pritiskom i","pritiskom i znatno","i znatno ublažila","znatno ublažila raniji","ublažila raniji odlazak","raniji odlazak u","odlazak u mirovinu","u mirovinu .","mirovinu . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
```

Belarusian (Cyrillic script):
```
"src":"[CLS] Першаклясьнік Багдан з маленства размаўляе толькі па-беларуску [EOS]","src_lab":"c c c c c c c c c","hyp":["[CLS] Першаклясьнік Багдан","Першаклясьнік Багдан з","Багдан з маленства","з маленства размаўляе","маленства размаўляе толькі","размаўляе толькі па-беларуску","толькі па-беларуску [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] І ўсё дзякуючы яго двум апошнім фільмам – “ Сума ” і “ Стрыптыз і вайна ” , якія аб’ехалі тузін самых важных дакументальных фестываляў свету . [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c c c c c c c c c c c c","hyp":["[CLS] І ўсё","І ўсё дзякуючы","ўсё дзякуючы яго","дзякуючы яго двум","яго двум апошнім","двум апошнім фільмам","апошнім фільмам –","фільмам – “","– “ Сума","“ Сума ”","Сума ” і","” і “","і “ Стрыптыз","“ Стрыптыз і","Стрыптыз і вайна","і вайна ”","вайна ” ,","” , якія",", якія аб’ехалі","якія аб’ехалі тузін","аб’ехалі тузін самых","тузін самых важных","самых важных дакументальных","важных дакументальных фестываляў","дакументальных фестываляў свету","фестываляў свету .","свету . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Падрыхтоўку макетаў найлепшых кніг падтрымае кампанія “ 5 элемент ” . [EOS]","src_lab":"c c c c c c c c c c c c c","hyp":["[CLS] Падрыхтоўку макетаў","Падрыхтоўку макетаў найлепшых","макетаў найлепшых кніг","найлепшых кніг падтрымае","кніг падтрымае кампанія","падтрымае кампанія “","кампанія “ 5","“ 5 элемент","5 элемент ”","элемент ” .","” . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] У яго нават не схілілася галава , каб папрасіць прабачэньня ў дзяцей і маці загінулых » [EOS]","src_lab":"c c c c c c c c c c c c c c c c c c","hyp":["[CLS] У яго","У яго нават","яго нават не","нават не схілілася","не схілілася галава","схілілася галава ,","галава , каб",", каб папрасіць","каб папрасіць прабачэньня","папрасіць прабачэньня ў","прабачэньня ў дзяцей","ў дзяцей і","дзяцей і маці","і маці загінулых","маці загінулых »","загінулых » [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Прыходзьце падтрымаць актывістаў . [EOS]","src_lab":"c c c c c c","hyp":["[CLS] Прыходзьце падтрымаць","Прыходзьце падтрымаць актывістаў","падтрымаць актывістаў .","актывістаў . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c"]}
{"src":"[CLS] На яе адваротным баку намаляваны калаж з дэкаратыўных элементаў будынка музея . [EOS]","src_lab":"c c c c c c c c c c c c c c","hyp":["[CLS] На яе","На яе адваротным","яе адваротным баку","адваротным баку намаляваны","баку намаляваны калаж","намаляваны калаж з","калаж з дэкаратыўных","з дэкаратыўных элементаў","дэкаратыўных элементаў будынка","элементаў будынка музея","будынка музея .","музея . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Фота NEXTA [EOS]","src_lab":"c c c c","hyp":["[CLS] Фота NEXTA","Фота NEXTA [EOS]"],"hyp_lab":["c c c","c c c"]}
{"src":"[CLS] Я ня ведаў , што яно будзе апублікаванае . [EOS]","src_lab":"c c c c c c c c c c c","hyp":["[CLS] Я ня","Я ня ведаў","ня ведаў ,","ведаў , што",", што яно","што яно будзе","яно будзе апублікаванае","будзе апублікаванае .","апублікаванае . [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Запрашаем на « Святочныя Беларускамоўныя » : <a_href=\"https://goo.gl/forms/2wMLPKN75EyouKa52\"> https://goo.gl/forms/2wMLPKN75EyouKa52 </a> [EOS]","src_lab":"c c c c c c c c c c c c","hyp":["[CLS] Запрашаем на","Запрашаем на «","на « Святочныя","« Святочныя Беларускамоўныя","Святочныя Беларускамоўныя »","Беларускамоўныя » :","» : <a_href=\"https://goo.gl/forms/2wMLPKN75EyouKa52\">",": <a_href=\"https://goo.gl/forms/2wMLPKN75EyouKa52\"> https://goo.gl/forms/2wMLPKN75EyouKa52","<a_href=\"https://goo.gl/forms/2wMLPKN75EyouKa52\"> https://goo.gl/forms/2wMLPKN75EyouKa52 </a>","https://goo.gl/forms/2wMLPKN75EyouKa52 </a> [EOS]"],"hyp_lab":["c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c","c c c"]}
{"src":"[CLS] Прыгожа ? [EOS]","src_lab":"c c c c","hyp":["[CLS] Прыгожа ?","Прыгожа ? [EOS]"],"hyp_lab":["c c c","c c c"]}
```

**Comment by EdwardZH** [comment]
The data set should be as follow:
{"src": "It 's difficult answer at the question \" what are you going to do in the future ? \" if the only one who has to know it is in two minds . [EOS]", "src_lab": "c c c i i c c c c c c c c c c c c c c c c c c c c c c c c c c c c c", "hyp": ["It 's difficult to answer the question \" what are you going to do in the future ? \" if the only one who has to know it is in two minds . [EOS]", "It 's difficult to answer the question \" what are you going to do in the future ? \" if the only one who has to know it is of two minds . [EOS]", "It 's difficult answer to the question \" what are you going to do in the future ? \" if the only one who has to know it is in two minds . [EOS]", "It 's difficult answer to the question \" what are you going to do in the future ? \" if the only one who has to know it is of two minds . [EOS]", "It 's difficult to answer the question \" what are you going to do in the future ? \" if the only one who has to know it is two minds . [EOS]"], "hyp_lab": ["c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c c", "c c c c c c c c c c c c c c c c c c c c c c c c c c c c c i c c c c", "c c c i i c c c c c c c c c c c c c c c c c c c c c c c c c c c c c", "c c c i i c c c c c c c c c c c c c c c c c c c c c c c c i c c c c", "c c c c c c c c c c c c c c c c c c c c c c c c c c c c c i c c c"]}
You should download our training data for reference.

**Comment by The-One-Who-Speaks-and-Depicts** [comment]
A, now I got how this works. Sorry, and thank you very much again!
